name: Docker CI/CD - Fullstack

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Fetch SSH secret and create key
        run: |
          aws secretsmanager get-secret-value \
            --secret-id fullstack/ssh \
            --query SecretString \
            --output text > ssh.json

          jq -r '.SERVER_SSH_KEY' ssh.json > github_actions_key
          chmod 600 github_actions_key

          echo "SERVER_HOST=$(jq -r .SERVER_HOST ssh.json)" >> $GITHUB_ENV
          echo "SERVER_USER=$(jq -r .SERVER_USER ssh.json)" >> $GITHUB_ENV
          echo "SSH_KEY_PATH=github_actions_key" >> $GITHUB_ENV

      - name: Copy docker-compose file
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ env.SERVER_HOST }}
          username: ${{ env.SERVER_USER }}
          key_path: ${{ env.SSH_KEY_PATH }}
          source: docker-compose.yml
          target: /home/ubuntu/fullstack

      - name: Deploy on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.SERVER_HOST }}
          username: ${{ env.SERVER_USER }}
          key_path: ${{ env.SSH_KEY_PATH }}
          script: |
            cd /home/ubuntu/fullstack
            docker compose down
            docker compose up -d --build
